-- SQLite

CREATE TABLE tasks (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title TEXT NOT NULL UNIQUE,
	description TEXT NOT NULL,
	status INTEGER NOT NULL
);

CREATE TABLE status (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	description TEXT NOT NULL
);